package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.Meters;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Twist2d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private Field2d field = new Field2d();
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /** Swerve request for field-centric driving with rotation control */
    private final SwerveRequest.FieldCentric alignRequest = new SwerveRequest.FieldCentric()
    .withDeadband(Constants.DriveConstants.TranslationDeadband)
    .withRotationalDeadband(Constants.DriveConstants.RotationDeadband);

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        SmartDashboard.putNumber("AutoMoveP", 1);
        SmartDashboard.putNumber("AutoMoveD", 1);  

                // Set up the chooser options
        BumDriveMode.setDefaultOption("Noah's driving", true);
        BumDriveMode.addOption("Noah's not driving", false);
        
        // Put the chooser on the dashboard
        SmartDashboard.putData("height Chooser", BumDriveMode);

        configureAutoBuilder();
        SmartDashboard.putData("field", field);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void configureAutoBuilder() {
        double tP = SmartDashboard.getNumber("AutoMoveP", 1);
        double tD = SmartDashboard.getNumber("AutoMoveD", 1);

        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(5, 0, 0), //TP ,  TD
                    // PID constants for rotation
                    new PIDConstants(5,0,0)//okherejakegay
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return Commands.run(() -> this.setControl(request.get()), this);
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }



    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    public Pose2d getPose() {
        return getState().Pose;
    }   


    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    // --------------------- END GENERATED CODE -------------------
    
    private double hubOffsetX = 0.0;
    private double hubOffsetY = 0.0;
    boolean Noahdrive = false;

    public void setHubOffset(double offsetX, double offsetY) {
    hubOffsetX += offsetX;
    hubOffsetY += offsetY;
    }

    public void resetHubOffset() {
    hubOffsetX = 0.0;
    hubOffsetY = 0.0;
    }
    
    private final SendableChooser<Boolean> BumDriveMode = new SendableChooser<>();

    // Get hub pose based on alliance
// Replace the existing static getHubPose() with this instance version
public Pose3d getHubPose() {
    Pose3d base = DriverStation.getAlliance()
        .map(alliance -> alliance == Alliance.Red ? Constants.FieldConstants.redHubPose : Constants.FieldConstants.blueHubPose).orElse(Constants.FieldConstants.blueHubPose);

    // Apply offsets relative to alliance
    // For Red alliance, flip X offset direction since field is mirrored
    double adjustedX = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red
        ? base.getX() - hubOffsetX
        : base.getX() + hubOffsetX;

    double adjustedY = base.getY() + hubOffsetY;

    return new Pose3d(adjustedX, adjustedY, base.getZ(), base.getRotation());
}

    
    public static Distance getCloseBumpY(Pose2d currentPose){
        if (currentPose.getMeasureY().gt(Inches.of(158.845))){
            return Inches.of(218.84);
        } else {
            return Inches.of(98.84);
        }
    }

    public static boolean isInAllianceZone(Pose2d robotPose){
        double robotX = robotPose.getX();
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        if (alliance == Alliance.Red) {
            return robotX > Inches.of(469.11).in(Meters);
        } else {
            return robotX < Inches.of(182.11).in(Meters);
            }
    }


    /**
     * Calculates the closest point on the predefined circle to the current robot pose.
     *
     * @return The closest point on the circle to the current robot position
     */

    public static final PIDController rotationController = getRotationController();

    private static PIDController getRotationController() {
        PIDController controller = new PIDController(Constants.DriveConstants.rotP,Constants.DriveConstants.rotI,Constants.DriveConstants.rotD);
        controller.enableContinuousInput(-Math.PI, Math.PI); // CRITICAL: enables wraparound at ±180°
        return controller;
    }

    private static final PIDController distanceController = getDistanceController();

    private static PIDController getDistanceController() {
        PIDController controller = new PIDController(Constants.DriveConstants.xyP, Constants.DriveConstants.xyI, Constants.DriveConstants.xyD); // Tune these values!
        return controller;
    }   

    public double getDistance(Pose2d drivePose){
        Pose2d hubPose = getHubPose().toPose2d();
        double currentDistance = drivePose.getTranslation().getDistance(hubPose.getTranslation());
        return currentDistance;
    }

    public Pose2d getTargetPose(Pose2d currentPose2d){
        final double thresholdY = Inches.of(158.32).in(Meters); //horizontal middle field line
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        if (alliance == Alliance.Red){
            if(isInAllianceZone(currentPose2d)){
                return getHubPose().toPose2d();
            }
            else if (currentPose2d.getY() >= thresholdY){
                return Constants.FieldConstants.redTargetHighPose;
            }
            else {
                return Constants.FieldConstants.redTargetLowPose;
            }
        }
        if (alliance == Alliance.Blue){
            if(isInAllianceZone(currentPose2d)){
                return getHubPose().toPose2d();
            }
            else if (currentPose2d.getY() >= thresholdY){
                return Constants.FieldConstants.blueTargetHighPose;
            }
            else {
                return Constants.FieldConstants.blueTargetLowPose;
            }
        }
        return null;
    }

    public Pose2d getShooter1Pose(Pose2d currentPose) {
        Translation2d offset = new Translation2d(0.103124, 0.2524252).rotateBy(currentPose.getRotation());
        return new Pose2d(currentPose.getTranslation().plus(offset), currentPose.getRotation());}
    public Pose2d getShooter2Pose(Pose2d currentPose) {
        Translation2d offset = new Translation2d(0.103124,0.0841502).rotateBy(currentPose.getRotation());
        return new Pose2d(currentPose.getTranslation().plus(offset), currentPose.getRotation());}
    public Pose2d getShooter3Pose(Pose2d currentPose) {
        Translation2d offset = new Translation2d(0.103124, -0.0841502).rotateBy(currentPose.getRotation());
        return new Pose2d(currentPose.getTranslation().plus(offset), currentPose.getRotation());}
    public Pose2d getShooter4Pose(Pose2d currentPose) {
        Translation2d offset = new Translation2d(0.103124, -0.2524252).rotateBy(currentPose.getRotation());
        return new Pose2d(currentPose.getTranslation().plus(offset), currentPose.getRotation());}

public double getShooter1DistanceInches() {
    Pose2d currentPose = getPose();
    return getShooter1Pose(currentPose).getTranslation().getDistance(getTargetPose(currentPose).getTranslation()) * 39.3701;
}

public double getShooter2DistanceInches() {
    Pose2d currentPose = getPose();
    return getShooter2Pose(currentPose).getTranslation().getDistance(getTargetPose(currentPose).getTranslation()) * 39.3701;
}

public double getShooter3DistanceInches() {
    Pose2d currentPose = getPose();
    return getShooter3Pose(currentPose).getTranslation().getDistance(getTargetPose(currentPose).getTranslation()) * 39.3701;
}

public double getShooter4DistanceInches() {
    Pose2d currentPose = getPose();
    return getShooter4Pose(currentPose).getTranslation().getDistance(getTargetPose(currentPose).getTranslation()) * 39.3701;
}

    public Pose2d ShootingLocation;

    public Command headingLocktoHub(CommandXboxController controller, double maxSpeed, double maxAngularRate) {
    return applyRequest(() -> {
        
        // Get current pose and target hub position
        Pose2d drivePose = getState().Pose;
        Pose2d targetPose = getTargetPose(drivePose);

        ShootingLocation = targetPose;
        
        // Calculate angle from hub to robot
        Translation2d toRobot = drivePose.getTranslation().minus(targetPose.getTranslation());

        Rotation2d angleToRobot = toRobot.getAngle();
        
        // Calculate desired rotation (face the hub)
        Rotation2d desiredAngle = angleToRobot.rotateBy(Rotation2d.k180deg); // Face toward hub | Take RotateBy out for back to face Hub
        Rotation2d currentAngle = drivePose.getRotation();
        
        // Calculate rotational rate to face hub
        double rotationalRate = rotationController.calculate(
            currentAngle.getRadians(), 
            desiredAngle.getRadians()
        );
        double xSpeed = MathUtil.applyDeadband(-controller.getLeftY(), 0.1);
        double ySpeed = MathUtil.applyDeadband(-controller.getLeftX(), 0.1);

        return alignRequest 
            .withVelocityX(xSpeed * maxSpeed)
            .withVelocityY(ySpeed * maxSpeed)
            .withRotationalRate(rotationalRate * maxAngularRate*1.5); 
    });
}

private boolean SlowTele = false;
public void ToggleSlowTele(){
    if (SlowTele == false) {SlowTele = true;}
    else if (SlowTele == true) {SlowTele = false;}
}

public Command TeleopDrive(CommandXboxController joystick, double MaxSpeed, double MaxAngularRate, SwerveRequest.FieldCentric drive, CommandSwerveDrivetrain drivetrain){
    return applyRequest(() -> {
        double xSpeed   = scaleAxis(MathUtil.applyDeadband(-joystick.getLeftY(), Constants.DriveConstants.TranslationDeadband));
        double ySpeed   = scaleAxis(MathUtil.applyDeadband(-joystick.getLeftX(), Constants.DriveConstants.TranslationDeadband));
        double rotSpeed = MathUtil.applyDeadband(-joystick.getRightX(), Constants.DriveConstants.TranslationDeadband);
        
        if (SlowTele){
            return alignRequest
                .withVelocityX(xSpeed * MaxSpeed * 0.5)
                .withVelocityY(ySpeed * MaxSpeed * 0.5)
                .withRotationalRate(rotSpeed * MaxAngularRate);
        }
        else {
            return alignRequest
            .withVelocityX(xSpeed * MaxSpeed)
            .withVelocityY(ySpeed * MaxSpeed)
            .withRotationalRate(rotSpeed * MaxAngularRate);
        }
    });
}

private double scaleAxis(double input) {
    double abs = Math.abs(input);
    if (abs == 0.0) return 0.0;
    abs = Math.min(abs, 1.0);
    double scaled = Math.pow(Math.sin((Math.PI / 2.0) * abs), 2); // no offset
    return Math.copySign(scaled, input);
}

public Command TeleopDriveSLOW(CommandXboxController joystick, double MaxSpeed, double MaxAngularRate, SwerveRequest.FieldCentric drive, CommandSwerveDrivetrain drivetrain){
    return applyRequest(() -> {
        double xSpeed   = scaleAxis(MathUtil.applyDeadband(-joystick.getLeftY(), 0.1));
        double ySpeed   = scaleAxis(MathUtil.applyDeadband(-joystick.getLeftX(), 0.1));
        double rotSpeed = MathUtil.applyDeadband(-joystick.getRightX(), 0.1);

        
        return alignRequest
            .withVelocityX(xSpeed * MaxSpeed * 0.75)
            .withVelocityY(ySpeed * MaxSpeed* 0.75)
            .withRotationalRate(rotSpeed * MaxAngularRate);
    });
}

    public static final InterpolatingDoubleTreeMap TOFmap = new InterpolatingDoubleTreeMap();
    static { //dist inch, time Sec
        TOFmap.put(53.7, 0.2); //53.7, 0.83 is real value
        TOFmap.put(70.8 , 1.0);
        TOFmap.put(100.3 , 1.2);
        TOFmap.put(112.5, 2.1);
    }



    public double lastAimAngleRad = Double.NaN;
 
    // Moving average filter over ~5 samples (at 50Hz that's ~0.1s of smoothing)
    // Smooths the noisy derivative of the aim angle to get a clean feedforward
    public final LinearFilter driveAngleFilter = LinearFilter.movingAverage(5);
 
    // Store last commanded speeds so we use setpoint velocity (not noisy measured)
    // Updated at the end of each SOTM loop, read at the start of the next
    public ChassisSpeeds lastCommandedSpeeds = new ChassisSpeeds();
 
    // Offset from robot center to the physical shooter position (measure from CAD)
    // Example: shooter is 0.2m forward and 0.0m sideways from robot center
    public static final Translation2d ROBOT_TO_SHOOTER = new Translation2d(0.2, 0.0);

    //BASED ON MECH A PRAISE THE FRC GODS FOR OPEN ALLIANCE
    public Command shootOnTheMoveIterative(CommandXboxController controller, double maxSpeed, double maxAngularRate) {
    return applyRequest(() -> {
 
        // ── 1. CURRENT STATE ─────────────────────────────────────────────────────
        Pose2d currentPose = getPose();
 
        // Use setpoint speeds (what we COMMANDED last loop) rather than noisy
        // measured wheel speeds. If first loop, fall back to measured.
        ChassisSpeeds measuredSpeeds = getState().Speeds;
        ChassisSpeeds robotRelativeSpeeds = (lastCommandedSpeeds.vxMetersPerSecond == 0
                && lastCommandedSpeeds.vyMetersPerSecond == 0
                && lastCommandedSpeeds.omegaRadiansPerSecond == 0)
                ? measuredSpeeds
                : lastCommandedSpeeds;
 
        // Convert to field-relative so we can do field-frame geometry
        ChassisSpeeds fieldVelocity = ChassisSpeeds.fromRobotRelativeSpeeds(
                robotRelativeSpeeds.vxMetersPerSecond,
                robotRelativeSpeeds.vyMetersPerSecond,
                robotRelativeSpeeds.omegaRadiansPerSecond,
                currentPose.getRotation()
        );
 
        // ── 2. PHASE DELAY (account for code→hardware latency) ───────────────────
        // 0.03s ≈ 1-2 loop cycles. This is NOT a full lookahead — it just shifts
        // the starting pose slightly to compensate for pipeline delay.
        double phaseDelay = 0.03;
        Pose2d estimatedPose = currentPose.exp(
                new Twist2d(
                        fieldVelocity.vxMetersPerSecond * phaseDelay,
                        fieldVelocity.vyMetersPerSecond * phaseDelay,
                        fieldVelocity.omegaRadiansPerSecond * phaseDelay
                )
        );
 
        // ── 3. SHOOTER POSITION (offset from robot center) ───────────────────────
        // Rotate the robot-frame offset into field frame using current heading.
        // If your shooter IS at center, set ROBOT_TO_SHOOTER = new Translation2d(0,0)
        Translation2d shooterOffsetFieldFrame = ROBOT_TO_SHOOTER.rotateBy(estimatedPose.getRotation());
        Translation2d shooterPosition = estimatedPose.getTranslation().plus(shooterOffsetFieldFrame);
 
        // ── 4. TARGET ─────────────────────────────────────────────────────────────
        Translation2d target = getTargetPose(currentPose).getTranslation();
 
        // ── 5. SHOOTER VELOCITY (field-relative, at shooter position) ────────────
        // The shooter is offset from the robot center, so it has additional
        // tangential velocity from the robot's rotation: v_tangential = omega × r
        // This is the same correction 6328 does with GeomUtil.transformVelocity()
        double omega = fieldVelocity.omegaRadiansPerSecond;
        // Tangential velocity added by rotation: perpendicular to the offset vector
        // If offset is (rx, ry), tangential is (-ry*omega, rx*omega)
        double shooterVelocityX = fieldVelocity.vxMetersPerSecond
                + (-shooterOffsetFieldFrame.getY() * omega);
        double shooterVelocityY = fieldVelocity.vyMetersPerSecond
                + (shooterOffsetFieldFrame.getX() * omega);


        double veloX = MathUtil.applyDeadband(-controller.getLeftY(), Constants.DriveConstants.TranslationDeadband);
        double veloY = MathUtil.applyDeadband(-controller.getLeftX(), Constants.DriveConstants.TranslationDeadband);
        //*************************************************************************************************************************** */
        boolean isRed = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;
        double allianceFlip = isRed ? -1.0 : 1.0;

        shooterVelocityX = fieldVelocity.vxMetersPerSecond * allianceFlip; //if allanice flup put it here
        shooterVelocityY = fieldVelocity.vyMetersPerSecond * allianceFlip;
 
        // ── 6. ITERATIVE LOOKAHEAD LOOP ───────────────────────────────────────────
        // Converges in ~3 iterations; 20 guarantees stability.
        // Each iteration: estimate TOF → predict where we'll be → recalc distance → repeat
        double timeOfFlight = 0.1; // initial guess
        Translation2d lookaheadShooterPosition = shooterPosition;
        double lookaheadDistance = target.getDistance(shooterPosition);
        
 
        for (int i = 0; i < 20; i++) {
            // Your TOF regression (distance in inches → time in seconds).
            // Replace this with your measured lookup table if you have one.
            double distInches = lookaheadDistance * 39.3701;
            timeOfFlight = TOFmap.get(distInches);
            timeOfFlight = Math.max(timeOfFlight, 0.05); // guard against degenerate values
            timeOfFlight = 1; //* ***************************************************************************************************** */
 
            // Where will the shooter be when the note arrives?
            double offsetX = shooterVelocityX * timeOfFlight * 0.15; //*0.25
            double offsetY = shooterVelocityY * timeOfFlight * 0.15;
            lookaheadShooterPosition = shooterPosition.plus(new Translation2d(offsetX, offsetY));
            lookaheadDistance = target.getDistance(lookaheadShooterPosition);
        }

 
        // ── 7. AIM ANGLE ──────────────────────────────────────────────────────────
        Rotation2d aimAngle = target.minus(lookaheadShooterPosition).getAngle();
 
        // ── 8. AIM ANGLE FEEDFORWARD ─────────────────────────────────────────────
        // 6328's key insight: differentiate the required aim angle over time and feed
        // that forward so the robot is already spinning at the right rate, not
        // just reacting to error. The filter removes noise from the derivative.
        double aimAngleRad = aimAngle.getRadians();
        double aimAngleVelocityFF = 0.0;
 
        if (!Double.isNaN(lastAimAngleRad)) {
            // Wrap the delta to handle the ±π boundary cleanly
            double rawDelta = aimAngleRad - lastAimAngleRad;
            // Normalize to [-π, π]
            while (rawDelta > Math.PI) rawDelta -= 2 * Math.PI;
            while (rawDelta < -Math.PI) rawDelta += 2 * Math.PI;
 
            double rawRate = rawDelta / 0.02; // 20ms loop period
            aimAngleVelocityFF = driveAngleFilter.calculate(rawRate);
        }
        lastAimAngleRad = aimAngleRad;
 
        // ── 9. ROTATION PID + FF ──────────────────────────────────────────────────
        Rotation2d currentAngle = currentPose.getRotation();
        double pidOutput = rotationController.calculate(currentAngle.getRadians(), aimAngleRad);
 
        // FF is in rad/s; scale it to match your maxAngularRate units.
        // Tune kFF: start at 1.0 and reduce if the robot overshoots on turns.
        double kFF = 0.25;//********************************************************************************************************************************************* */
        double rotationalRate = aimAngleVelocityFF * kFF + pidOutput;
 
        // ── 10. DRIVER TRANSLATION INPUT ───────────────────────────────────────── *******************************************UN COMMENT
        //double veloX = MathUtil.applyDeadband(-controller.getLeftY(), Constants.DriveConstants.TranslationDeadband);
        //double veloY = MathUtil.applyDeadband(-controller.getLeftX(), Constants.DriveConstants.TranslationDeadband);
 
        // ── 12. BUILD COMMANDED SPEEDS & CACHE THEM ───────────────────────────────
        // Cache what we're about to command so next loop uses setpoint, not measured
        // Convert field-relative driver input back to robot-relative for storage
        ChassisSpeeds fieldRelativeCommanded = new ChassisSpeeds(
                veloX * maxSpeed,
                veloY * maxSpeed,
                rotationalRate * maxAngularRate
        );
        lastCommandedSpeeds = ChassisSpeeds.fromFieldRelativeSpeeds(
                fieldRelativeCommanded, currentPose.getRotation()
        );
 
        // ── 13. VISUALIZATION ─────────────────────────────────────────────────────
        ShootingLocation = new Pose2d(lookaheadShooterPosition, aimAngle);
 
        SmartDashboard.putNumber("SOTM/AimAngleDeg", Math.toDegrees(aimAngleRad));
        SmartDashboard.putNumber("SOTM/LookaheadDistanceMeters", lookaheadDistance);
        SmartDashboard.putNumber("SOTM/LookaheadDistanceMeters", lookaheadDistance * 39.3701);
        SmartDashboard.putNumber("SOTM/TimeOfFlight", timeOfFlight);
        SmartDashboard.putNumber("SOTM/AimAngleFFRadPerSec", aimAngleVelocityFF);
        SmartDashboard.putNumber("SOTM/AimErrorDeg",aimAngle.minus(currentAngle).getDegrees());
        SmartDashboard.putNumber("SOTM/shooterVelocityX", shooterVelocityX);
        SmartDashboard.putNumber("SOTM/shooterVelocityY", shooterVelocityY);
        SmartDashboard.putNumber("SOTM/lookaheadOffsetX", lookaheadShooterPosition.getX() - shooterPosition.getX());
        SmartDashboard.putNumber("SOTM/lookaheadOffsetY", lookaheadShooterPosition.getY() - shooterPosition.getY());
        SmartDashboard.putNumber("SOTM/shooterPosX", shooterPosition.getX());
        SmartDashboard.putNumber("SOTM/shooterPosY", shooterPosition.getY());
        SmartDashboard.putNumber("SOTM/lookaheadPosX", lookaheadShooterPosition.getX());
        SmartDashboard.putNumber("SOTM/lookaheadPosY", lookaheadShooterPosition.getY());
        SmartDashboard.putNumber("SOTM/targetX", target.getX());
        SmartDashboard.putNumber("SOTM/targetY", target.getY());
        SmartDashboard.putNumber("SOTM/aimAngleDeg", Math.toDegrees(aimAngleRad));
        SmartDashboard.putNumber("SOTM/currentAngleDeg", currentPose.getRotation().getDegrees());
        SmartDashboard.putNumber("SOTM/pidOutput", pidOutput);
        SmartDashboard.putNumber("SOTM/rotationalRate", rotationalRate);
 
        // ── 14. APPLY REQUEST ─────────────────────────────────────────────────────
        return alignRequest
                .withVelocityX(veloX * maxSpeed * 0.2)
                .withVelocityY(veloY * maxSpeed*  0.2)
                .withRotationalRate(rotationalRate * maxAngularRate);
    });
}

public Pose2d getLookaheadPose() {
    if (ShootingLocation == null) return getPose(); // fallback to current distance
    return ShootingLocation;
}

public double getLookaheadDistance() {
    if (ShootingLocation == null) return getDistance(getPose()); // fallback to current distance
    Pose2d hubPose = getHubPose().toPose2d();
    return ShootingLocation.getTranslation().getDistance(hubPose.getTranslation());
}


public boolean isAimedAtTarget() {
    Pose2d currentPose = getPose();
    Rotation2d currentAngle = currentPose.getRotation();
    
    // Calculate required aim angle (same as headingLocktoHub)
    Translation2d target = getTargetPose(currentPose).getTranslation();
    Translation2d toTarget = target.minus(currentPose.getTranslation());
    Rotation2d targetAngle = toTarget.getAngle(); // Face towards from hub .plus(Krot180) or sum idk
    
    // Calculate angle error
    double errorDegrees = Math.abs(targetAngle.minus(currentAngle).getDegrees());
    SmartDashboard.putNumber("errorDegrees", errorDegrees);
    
    return errorDegrees <= Constants.DriveConstants.RotationalToleranceDegrees;
}

public boolean isAimedAtTargetAuto() {
    Pose2d currentPose = getPose();
    Rotation2d currentAngle = currentPose.getRotation();
    
    // Calculate required aim angle (same as headingLocktoHub)
    Translation2d target = getTargetPose(currentPose).getTranslation();
    Translation2d toTarget = target.minus(currentPose.getTranslation());
    Rotation2d targetAngle = toTarget.getAngle(); // Face towards from hub .plus(Krot180) or sum idk
    
    // Calculate angle error
    double errorDegrees = Math.abs(targetAngle.minus(currentAngle).getDegrees());
    SmartDashboard.putNumber("errorDegrees", errorDegrees);
    
    return errorDegrees <= Constants.DriveConstants.RotationalToleranceDegreesAUTO;
}

public boolean isAimedAtTargetSOTM() {
    if (ShootingLocation == null) return false;
    
    Pose2d currentPose = getPose();
    Rotation2d currentAngle = currentPose.getRotation();
    
    // ShootingLocation.getRotation() is the SOTM aim angle (set each loop in step 13)
    Rotation2d targetAngle = ShootingLocation.getRotation();
    
    double errorDegrees = Math.abs(targetAngle.minus(currentAngle).getDegrees());
    SmartDashboard.putNumber("SOTM/errorDegrees", errorDegrees);
    
    return errorDegrees <= Constants.DriveConstants.RotationalToleranceDegrees + 2;
}


public Command bumpLockCommand(SwerveRequest.FieldCentric drive, CommandSwerveDrivetrain drivetrain, CommandXboxController joystick, Double MaxSpeed, double MaxAngularRate){
        boolean isRed = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;

        Rotation2d rotSetpoint = isInAllianceZone(drivetrain.getPose())
            ? (isRed ? Rotation2d.kZero : Rotation2d.fromDegrees(180))
            : (isRed ? Rotation2d.fromDegrees(180) : Rotation2d.kZero);
    
    return applyRequest(() -> {
        double closeTrench = (double)getCloseBumpY(drivetrain.getPose()).in(Meters);
        double xSpeed = MathUtil.applyDeadband(-joystick.getLeftY(), 0.1);
        double ySpeed = MathUtil.applyDeadband(-joystick.getLeftX(), 0.1);

        double robotY = drivetrain.getPose().getY();
        double error = robotY - closeTrench;
        double borderLimit = Inches.of(18).in(Meters);
        double distToTrench = Math.abs(error);
        double borderY = closeTrench + Math.copySign(borderLimit, error);

        double ySpeedFieldRelative = isRed ? -ySpeed : ySpeed;
        boolean pushingAway = (error > 0 && ySpeedFieldRelative > 0) || (error < 0 && ySpeedFieldRelative < 0);

        double yVel;
        if (distToTrench > borderLimit) {
            distanceController.setSetpoint(closeTrench);
            yVel = distanceController.calculate(robotY);
            if (isRed) yVel = -yVel; // flip PID output for Red
        } else if (pushingAway) {
            distanceController.setSetpoint(borderY);
            yVel = distanceController.calculate(robotY);
            if (isRed) yVel = -yVel; // flip PID output for Red
        } else {
            if (ySpeed == 0) {
                // No joystick input — auto-center to trench
                distanceController.setSetpoint(closeTrench);
                yVel = distanceController.calculate(robotY);
                if (isRed) yVel = -yVel;
            } else {
                // Driver pushing inward — full driver control
                yVel = ySpeed;
            }
        }
        rotationController.setSetpoint(rotSetpoint.getRadians());

        double rotSpeedToStraight = rotationController.calculate(drivetrain.getPose().getRotation().getRadians());
        if (rotationController.atSetpoint()) rotSpeedToStraight = 0;

        return drive
            .withVelocityX(xSpeed * MaxSpeed)
            .withVelocityY(yVel * MaxSpeed) // no negation
            .withRotationalRate(rotSpeedToStraight * MaxAngularRate);
    });
}

    private double SnakeDriveMult = 0.75;

        public Command getSnakeDriveCommand(SwerveRequest.FieldCentric drive, CommandSwerveDrivetrain drivetrain, CommandXboxController joystick, Double MaxSpeed, double MaxAngularRate) {
            return applyRequest(() -> {
                Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);

                double xSpeed   = scaleAxis(MathUtil.applyDeadband(-joystick.getLeftY(), Constants.DriveConstants.TranslationDeadband));
                double ySpeed   = scaleAxis(MathUtil.applyDeadband(-joystick.getLeftX(), Constants.DriveConstants.TranslationDeadband));

                double xVelocity = xSpeed * MaxSpeed;
                double yVelocity = ySpeed * MaxSpeed;

                double rotInput = MathUtil.applyDeadband(-joystick.getRightX(), 0.1); // override deadband

                double rotationRate = 0;

                if (Math.abs(rotInput) > 0) {
                    // Joystick override — bypass snake drive
                    rotationRate = rotInput * MaxAngularRate;
                } else {
                    double translationMagnitude = Math.hypot(xVelocity, yVelocity);
                    if (translationMagnitude > Constants.DriveConstants.TranslationDeadband) {
                        Rotation2d targetHeading;
                        if (alliance.equals(Alliance.Red)) {
                            targetHeading = new Rotation2d(xVelocity, yVelocity);
                        } else {
                            targetHeading = new Rotation2d(xVelocity, yVelocity).rotateBy(Rotation2d.k180deg);
                        }
                        Rotation2d currentHeading = drivetrain.getState().Pose.getRotation();
                        double headingError = targetHeading.minus(currentHeading).getRadians();
                        rotationRate = Math.max(-MaxAngularRate, Math.min(MaxAngularRate, headingError * Constants.DriveConstants.rotP * 5));
                    }
                }

                return drive
                    .withVelocityX(xVelocity *  SnakeDriveMult)
                    .withVelocityY(yVelocity * SnakeDriveMult)
                    .withRotationalRate(rotationRate);
            });
        }


    @Override
    public void periodic() {
        if(ShootingLocation != null){field.getObject("Shooting Target").setPose(ShootingLocation);}
        field.setRobotPose(getPose());
        SmartDashboard.putNumber("distanceToCenterHubInches", getDistance(getPose()) * 39.3701);
        SmartDashboard.putNumber("Hub/OffsetX", hubOffsetX);
        SmartDashboard.putNumber("Hub/OffsetY", hubOffsetY);
        SmartDashboard.putBoolean("SlowDrive?", SlowTele);
        SmartDashboard.putNumber("Shooter1DistInches", getShooter1DistanceInches());
        SmartDashboard.putNumber("Shooter2DistInches", getShooter2DistanceInches());
        SmartDashboard.putNumber("Shooter3DistInches", getShooter3DistanceInches());
        SmartDashboard.putNumber("Shooter4DistInches", getShooter4DistanceInches());

        Noahdrive = BumDriveMode.getSelected();

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }
}