package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveRequest.FieldCentric;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Twist2d;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import edu.wpi.first.units.*;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private Field2d field = new Field2d();
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /** Swerve request for field-centric driving with rotation control */
    private final SwerveRequest.FieldCentric alignRequest = new SwerveRequest.FieldCentric()
    .withDeadband(Constants.DriveConstants.TranslationDeadband)
    .withRotationalDeadband(Constants.DriveConstants.RotationDeadband);

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();



    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
        SmartDashboard.putData("field", field);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(Constants.DriveConstants.xyP, Constants.DriveConstants.xyI, Constants.DriveConstants.xyD),
                    // PID constants for rotation
                    new PIDConstants(Constants.DriveConstants.rotP,Constants.DriveConstants.rotI,Constants.DriveConstants.rotD)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return Commands.run(() -> this.setControl(request.get()), this);
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }



    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    public Pose2d getPose() {
        return getState().Pose;
    }   


    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    // Hub poses for each alliance
    
    // Get hub pose based on alliance
    public static Pose3d getHubPose() {
        return DriverStation.getAlliance()
            .map(alliance -> alliance == Alliance.Red ? Constants.FieldConstants.redHubPose : Constants.FieldConstants.blueHubPose)
            .orElse(Constants.FieldConstants.blueHubPose); // Default to blue if alliance unknown
    }

    public static Pose2d getTargetPose(double robotX, double robotY) {
    Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
    if (alliance == Alliance.Red) {
        return robotX > 250
            ? (robotY > 158.32 ? Constants.FieldConstants.redTargetHighPose : Constants.FieldConstants.redTargetLowPose)
            : Constants.FieldConstants.redHubPose.toPose2d();
    } else {
        return robotX < 250
            ? (robotY > 158.32 ? Constants.FieldConstants.blueTargetHighPose : Constants.FieldConstants.blueTargetLowPose)
            : Constants.FieldConstants.blueHubPose.toPose2d();
    }
}

    /**
     * Calculates the closest point on the predefined circle to the current robot pose.
     *
     * @return The closest point on the circle to the current robot position
     */
    public Pose2d getClosestPointOnHub() {

        Pose2d hub = getHubPose().toPose2d();
        Pose2d currentPose = getPose();
        
        // Calculate vector from center to current position
        double deltaX = currentPose.getX() - hub.getX();
        double deltaY = currentPose.getY() - hub.getY();
        
        // Calculate angle from center to current position
        double angle = Math.atan2(deltaY, deltaX);
        
        // Calculate the closest point on the circle
        double closestX = hub.getX() + Constants.ShooterConstants.ShootingDistance * Math.cos(angle);
        double closestY = hub.getY() + Constants.ShooterConstants.ShootingDistance * Math.sin(angle);
        
        return new Pose2d(closestX, closestY, new Rotation2d(angle));
    }

    public static final PIDController rotationController = getRotationController();

    private static PIDController getRotationController() {
        PIDController controller = new PIDController(Constants.DriveConstants.rotP,Constants.DriveConstants.rotI,Constants.DriveConstants.rotD);
        controller.enableContinuousInput(-Math.PI, Math.PI); // CRITICAL: enables wraparound at ±180°
        return controller;
    }

    private static final PIDController distanceController = getDistanceController();

    private static PIDController getDistanceController() {
        PIDController controller = new PIDController(Constants.DriveConstants.xyP, Constants.DriveConstants.xyI, Constants.DriveConstants.xyD); // Tune these values!
        return controller;
    }   

    public double getDistance(){
        Pose2d drivePose = getState().Pose;
        Pose2d hubPose = getHubPose().toPose2d();
        double currentDistance = drivePose.getTranslation().getDistance(hubPose.getTranslation());
        return currentDistance;
    }







    Pose2d ShootingLocation;
public Command headingLocktoHub(CommandXboxController controller, double maxSpeed, double maxAngularRate, String tuning) {
    return applyRequest(() -> {

        Pose2d drivePose = getState().Pose;
        Pose2d targetPose = getTargetPose(drivePose.getX(), drivePose.getY());

        ShootingLocation = targetPose;

        Translation2d toRobot = drivePose.getTranslation().minus(targetPose.getTranslation());
        Rotation2d angleToRobot = toRobot.getAngle();
        
        Rotation2d desiredAngle = angleToRobot.rotateBy(Rotation2d.k180deg);
        Rotation2d currentAngle = drivePose.getRotation();

        if (Math.abs(desiredAngle.getDegrees() - currentAngle.getDegrees()) <= 1) {
            desiredAngle = currentAngle;
        }
        
        double rotationalRate = rotationController.calculate(
            currentAngle.getRadians(), 
            desiredAngle.getRadians()
        );

        double veloX = -controller.getLeftY();
        if (Math.abs(veloX) < 0.1) veloX = 0;

        double veloY = -controller.getLeftX();
        if (Math.abs(veloY) < 0.1) veloY = 0;

        if (tuning.equals("PovLeft"))  { veloX = 0; veloY =  0.3; }
        if (tuning.equals("PovRight")) { veloX = 0; veloY = -0.3; }

        SmartDashboard.putNumber("Target/X", targetPose.getX());
        SmartDashboard.putNumber("Target/Y", targetPose.getY());
        SmartDashboard.putNumber("Robot/X", drivePose.getX());
        SmartDashboard.putNumber("Robot/Y", drivePose.getY());

        return alignRequest
            .withVelocityX(veloX * maxSpeed)
            .withVelocityY(veloY * maxSpeed)
            .withRotationalRate(rotationalRate * maxAngularRate);
    });
}






    public Command TeleopDrive(CommandXboxController joystick, double MaxSpeed, double MaxAngularRate, SwerveRequest.FieldCentric drive, CommandSwerveDrivetrain drivetrain){
        return applyRequest(() ->{
                return alignRequest.withVelocityX(-joystick.getLeftY() * MaxSpeed).withDeadband(Constants.DriveConstants.TranslationDeadband) // Drive forward with negative Y (forward) DriveStraight = robot centric 
                    .withVelocityY(-joystick.getLeftX() * MaxSpeed).withDeadband(Constants.DriveConstants.TranslationDeadband) // Drive left with negative X (left)
                    .withRotationalRate(-joystick.getRightX() * MaxAngularRate).withDeadband(Constants.DriveConstants.RotationDeadband);} // Drive counterclockwise with negative X (left)
            ); }

    double futureDistance = 0.0;
    public double GetFutureDistMeters(){
        Pose2d robotPose = getPose();
        double distance = getDistance();
        ChassisSpeeds fieldSpeeds = getState().Speeds;
        Pose2d actualHub = getHubPose().toPose2d();

           // Convert field speeds to robot-relative
        ChassisSpeeds robotSpeeds = ChassisSpeeds.fromFieldRelativeSpeeds(
        fieldSpeeds.vxMetersPerSecond,
        fieldSpeeds.vyMetersPerSecond,
        fieldSpeeds.omegaRadiansPerSecond,
        robotPose.getRotation().unaryMinus() // Inverse rotation
            );
        
        // Step 2: Predict where ROBOT will be
        double futureRobotX = robotPose.getX() + (robotSpeeds.vxMetersPerSecond);
        double futureRobotY = robotPose.getY() + (robotSpeeds.vyMetersPerSecond);
        Translation2d futureRobotPos = new Translation2d(futureRobotX, futureRobotY);
        
        // Step 3: Calculate angle from future robot position to hub
        Translation2d futureToHub = actualHub.getTranslation().minus(futureRobotPos);
        futureDistance = futureToHub.getNorm();
        return futureDistance;
    }

    //BASED ON MECH A PRAISE THE FRC GODS FOR OPEN ALLIANCE
    public Command shootOnTheMoveIterative(CommandXboxController controller, double maxSpeed, double maxAngularRate, String tuning) {
    return applyRequest(() -> {
        // === 6328 SHOOTING ALGORITHM ===
        
        // 1. Get current state
        Pose2d currentPose = getPose();
        ChassisSpeeds robotRelativeSpeeds = getState().Speeds;
        
        // CRITICAL: Convert robot-relative speeds to field-relative
        ChassisSpeeds fieldVelocity = ChassisSpeeds.fromRobotRelativeSpeeds(
            robotRelativeSpeeds.vxMetersPerSecond,
            robotRelativeSpeeds.vyMetersPerSecond,
            robotRelativeSpeeds.omegaRadiansPerSecond,
            currentPose.getRotation()
        );
        
        // 2. Phase delay - predict where robot will be
        double phaseDelay = 0.25;
        Pose2d estimatedPose = currentPose.exp(
            new Twist2d(
                fieldVelocity.vxMetersPerSecond * phaseDelay,
                fieldVelocity.vyMetersPerSecond * phaseDelay,
                fieldVelocity.omegaRadiansPerSecond * phaseDelay
            )
        );
        
        // 3. Get target (hub position)
        Translation2d target = getHubPose().toPose2d().getTranslation();
        
        // 4. Shooter position
        Translation2d shooterPosition = estimatedPose.getTranslation();
        
        // 5. Field-relative shooter velocity
        double shooterVelocityX = fieldVelocity.vxMetersPerSecond;
        double shooterVelocityY = fieldVelocity.vyMetersPerSecond;
        
        // 6. ITERATIVE LOOP
        double timeOfFlight = 0.0;
        Translation2d lookaheadShooterPosition = shooterPosition;
        double lookaheadDistance = target.getDistance(shooterPosition);
        
        for (int i = 0; i < 20; i++) {
            double distInches = lookaheadDistance * 39.3701;
            timeOfFlight = 0.0115177* distInches +0.330879;
            
            if (timeOfFlight < 0.01) {
                timeOfFlight = 0.1;
            }
            
            double offsetX = shooterVelocityX *timeOfFlight ; //times both of these by TOF for real robot
            double offsetY = shooterVelocityY *timeOfFlight;
            
            lookaheadShooterPosition = shooterPosition.plus(new Translation2d(offsetX, offsetY));
            lookaheadDistance = target.getDistance(lookaheadShooterPosition);
        }
        
        // 7. Calculate aim angle
        Rotation2d aimAngle = target.minus(lookaheadShooterPosition).getAngle();
        
        // === ROTATION CONTROL ===
        Rotation2d currentAngle = currentPose.getRotation();
        
        double rotationalRate = rotationController.calculate(
            currentAngle.getRadians(), 
            aimAngle.getRadians()
        );
        
        // Driver inputs
        double veloX = -controller.getLeftY();
        if (Math.abs(veloX) < Constants.DriveConstants.TranslationDeadband) {
            veloX = 0;
        }

        double veloY = -controller.getLeftX();
        if (Math.abs(veloY) < Constants.DriveConstants.TranslationDeadband) {
            veloY = 0;
        }
        
        if (tuning.equals("PovLeft")) { veloX = 0; veloY = 0.3; }
        if (tuning.equals("PovRight")) { veloX = 0; veloY = -0.3; }
        
        // Visualization
        ShootingLocation = new Pose2d(lookaheadShooterPosition, aimAngle);
        
        // Debug
        SmartDashboard.putNumber("Shot/Robot Vx", robotRelativeSpeeds.vxMetersPerSecond);
        SmartDashboard.putNumber("Shot/Robot Vy", robotRelativeSpeeds.vyMetersPerSecond);
        SmartDashboard.putNumber("Shot/Field Vx", fieldVelocity.vxMetersPerSecond);
        SmartDashboard.putNumber("Shot/Field Vy", fieldVelocity.vyMetersPerSecond);
        SmartDashboard.putNumber("Shot/Lookahead Distance", lookaheadDistance);
        SmartDashboard.putNumber("Shot/Time of Flight", timeOfFlight);
        SmartDashboard.putNumber("Shot/Current Angle", currentAngle.getDegrees());
        SmartDashboard.putNumber("Shot/Aim Angle", aimAngle.getDegrees());
        SmartDashboard.putNumber("Shot/Rotational Rate", rotationalRate);
        SmartDashboard.putNumber("Shot/Prediction Offset X", lookaheadShooterPosition.getX() - currentPose.getX());
        SmartDashboard.putNumber("Shot/Prediction Offset Y", lookaheadShooterPosition.getY() - currentPose.getY());
        SmartDashboard.putNumber("Shot/Angle Error Deg", aimAngle.minus(currentAngle).getDegrees());
        
        return alignRequest
            .withVelocityX(veloX * maxSpeed) 
            .withVelocityY(veloY * maxSpeed) 
            .withRotationalRate(rotationalRate);
    });
}

public boolean isAimedAtTarget() {
    Pose2d currentPose = getPose();
    Rotation2d currentAngle = currentPose.getRotation();
    
    // Calculate required aim angle (same as headingLocktoHub)
    Translation2d target = getHubPose().toPose2d().getTranslation();
    Translation2d toTarget = target.minus(currentPose.getTranslation());
    Rotation2d targetAngle = toTarget.getAngle(); // Face toward hub
    
    // Calculate angle error
    double errorDegrees = Math.abs(targetAngle.minus(currentAngle).getDegrees());
    SmartDashboard.putNumber("errorDegrees", errorDegrees);
    
    return errorDegrees <= Constants.DriveConstants.RotationalToleranceDegrees;
}

public Command getSnakeDriveCommand(SwerveRequest.FieldCentric drive, CommandSwerveDrivetrain drivetrain, CommandXboxController joystick, Double MaxSpeed, double MaxAngularRate) {
        return applyRequest(() -> {
            // Get joystick inputs
            double xSpeed = MathUtil.applyDeadband(-joystick.getLeftY(), Constants.DriveConstants.TranslationDeadband);
            double ySpeed = MathUtil.applyDeadband(-joystick.getLeftX(), Constants.DriveConstants.TranslationDeadband);
            
            // Convert to velocities
            double xVelocity = xSpeed * MaxSpeed;
            double yVelocity = ySpeed * MaxSpeed;
            
            // Calculate rotation for snake drive
            double rotationRate = 0;
            double translationMagnitude = Math.hypot(xVelocity, yVelocity);
            
            if (translationMagnitude > Constants.DriveConstants.TranslationDeadband) {
                // Calculate target heading from joystick direction
                Rotation2d targetHeading = new Rotation2d(xVelocity, yVelocity).rotateBy(Rotation2d.k180deg);
                
                // Get current heading
                Rotation2d currentHeading = drivetrain.getState().Pose.getRotation();
                
                // Calculate shortest path error
                double headingError = targetHeading.minus(currentHeading).getRadians();
                
                // P controller for rotation
                rotationRate = headingError * Constants.DriveConstants.rotP*5;
                
                // Clamp to max rotation rate 
                
                rotationRate = Math.max(-MaxAngularRate, 
                                       Math.min(MaxAngularRate, rotationRate));
                
            }
            
            return drive
                .withVelocityX(xVelocity)
                .withVelocityY(yVelocity)
                .withRotationalRate(rotationRate);
        });
    }


    @Override
    public void periodic() {
        SmartDashboard.putNumber("ShootingDistance", Constants.ShooterConstants.ShootingDistance*3.28084); //3.28084 Feet per Meter (converting Meters to Feet)
        if(ShootingLocation != null){field.getObject("Shooting Target").setPose(ShootingLocation);}
        field.setRobotPose(getPose());

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }
}